### ISSUE TITLE
[signin_signup] Create sign in and sign up for user alumni

### ISSUE THREAD

**Issue by ghost** [pnc-virtual-company/2021-G9-VC2-PART2#6]
We create interface sign in and sign up for user alumni.

**Comment by ghost** [comment]
@Sreypichly 
@Sethmok 
@ronanpnc 
@prosnob 
Good afternoon, teacher. As we had a meeting this morning, I think you are not clear with the process of sign in and sign up. We just want to clarify that sign up for alumni will have two steps and we explain you in the picture below. If you are still not clear, we can arrange a small meeting again today.
Note: In the picture, we just explain the process of sign in and sign up, we don't focus on the interface.

link: ![signin_signup](https://user-images.githubusercontent.com/73749242/146740054-f10fbbf2-ed46-4cf0-a81e-f1fa7966615b.png)

**Comment by VuthyWA** [comment]
@Sreypichly
@Sethmok
@ronanpnc 

Good morning, teacher. I hope all of you are doing well. I am sending this message to inform you about my mockup for sign in and sign up for alumni. You can see the mockup in the link below. If you have any feedback, please drop me here. 
Thank you.

link:
[VC2-PART-2 (5).pdf](https://github.com/pnc-virtual-company/2021-G9-VC2-PART2/files/7748915/VC2-PART-2.5.pdf)

**Comment by Sethmok** [comment]
@sinetsem

In step 2, how does the admin invite alumni to create an account? Is it by email or verified by alumni name? 

Best,

**Comment by VuthyWA** [comment]
@Sethmok 

Hello Teacher 
Sinet is busy today.
For invitation the alumnis if we invite by email it will be more easy than by full name and batch (it will have many problems relate to that).
- invite by email you can invite a group of people at one time. (we just collect email from alumni only one time)
+ How to invite :
     - If you are a admin of the application you will have a field to put a group their email and click on button invite to invite them.
+ Are you agree to change to invite by email?
      after you click on button invite it can  auto sent really email to alert them or you just sent email to them by yourself.
+ Note : if you still not clear we can have quick meeting because we are late now.
Thank you,
